### PR TITLE
[FIX] Replace only single percent signs with regex

### PR DESCRIPTION
**Pull request by kusha**

### CODE REVIEW

**Review by Didah — APPROVED** [review]

**Comment by DriesOeyen** [comment]
Not a show-stopper for 3.14, but this PR and #3 seem to be based on a misunderstanding of what this fork is trying to accomplish: compatibility with both `{new_style}` and `%(old_style)s` placeholders. Consider the following example:

```py
>>> def _esc(string):
...     return re.sub(r"(?<!\%)\%{1}(?!\%)", "%%", string)
...
>>> vars = {"foo": "bar"}
>>> s_new = "See you at the {foo}, I'm 100% ready for anything but 0%% drinks!"
>>> s_old = "See you at the %(foo)s, I'm 100% ready for anything but 0%% drinks!"
>>> _esc(s_new.format(**vars)) % vars
"See you at the bar, I'm 100% ready for anything but 0% drinks!"
                ^^^ OK      ^ OK                      ^ OK
>>> _esc(s_old.format(**vars)) % vars
"See you at the %(foo)s, I'm 100% ready for anything but 0% drinks!"
                ^^^^^^^ Broken  ^ OK                      ^ OK
```

As you can see, you've successfully made it so that we no longer choke on a single `%` sign, but you've traded it for the ability to use old-style placeholders at all. This basically means that, in a very roundabout way, you're just doing the following now:

```py
s.format(**vars)  # Rationale: the regex "_esc" function cancels out old-style %-based formatting
```

In conclusion: the necessity to escape `%` signs as `%%` in tagged strings is a necessary compromise to support both old-style and new-style placeholders. And indeed, while a single `%` will result in an exception, we built a safety net for this case in the PO file checker Action. This Action is supposed to catch instances where a translator has entered a single % sign instead of 2 in a row (although I now see the implementation could be improved a bit, I believe it can be misled by 2 separate unescaped percentage signs in a single string).
https://github.com/bewellinnovations/incasa-web/blob/master/.github/scripts/po_file_checker.py#L50-L72

Why can we enforce the rule "never use a single % sign" as an Action in incasa-web? Because for that specific project, we've made the conscious decision to use only new-style placeholders. Aka: an `%(old_style)s` placeholder would also cause this test to fail (just like a single `%` sign), but it's supposed to because we should use a `{new_style}` placeholder in the tagged string. This is also why there is no actual impact and this doesn't block the release of 3.14.

**Comment by Didah** [comment]
>(although I now see the implementation could be improved a bit, I believe it can be misled by 2 separate unescaped percentage signs in a single string).
> https://github.com/bewellinnovations/incasa-web/blob/master/.github/scripts/po_file_checker.py#L50-L72

No, the regex in that test is looking for occurences of 1 or more **consecutive** `%` and building a list of them, then checking each item in that list:

```
>>> import re
>>> re.findall(r"%+", "%")
['%']
>>> re.findall(r"%+", "%blah%")
['%', '%']
>>> re.findall(r"%+", "%%blah%")
['%%', '%']
```

You're right that we need to handle the changes to the fork's gettext differently so as not to break the old style placeholders though!

**Comment by DriesOeyen** [comment]
Current Action logic looking good then. 👌 Sorry about that, that particular comment was based on just a (very) diagonal look. 😄

**Comment by Didah** [comment]
> Current Action logic looking good then. 👌 Sorry about that, that particular comment was based on just a (very) diagonal look. 😄

No worries! Always good to doublecheck. 🙌

**Pull request merged**
